### ISSUE TITLE
iPhone won't navigate to App Store

### ISSUE THREAD

**Issue by jbw91** [pushandplay/cordova-plugin-apprate#154] opened 2017-02-02 03:10 UTC
When using this plugin in my app on an Android device, it works properly, shows the popup, and navigates you to the Google Play store. When running the same app on my iPhone running iOS 10.2+, the popup is never presented.

**Comment by jbw91** [comment] 2017-02-02 18:29
Just did some further research. When you are using a custom locale:

```javascript
AppRate.preferences.customLocale = {
  title: 'Leave a Review',
  message: 'If you like the game, consider giving it 5 stars!',
  cancelButtonLabel: 'Pass',
  rateButtonLabel: 'Rate it!',
  laterButtonLabel: 'Later'
};
```

Then the popup is never shown due to the code in the `showDialog` function. You have the code on [Lines 89-95](https://github.com/pushandplay/cordova-plugin-apprate/blob/master/www/AppRate.js#L89-L95) which checks that property, and if you're not using a custom locale, it doesn't ever show the popup.

So by removing the customLocale and simply using the default one, the popup now appears. However, When you click on the Leave a Review button, it doesn't ever open the app store.

**Comment by Panajev** [comment] 2017-02-15 10:58
Hello @jbw91,

I have tried to do the following on the JS side (app running on iOS 10.2.1 device):
```
AppRate.preferences.storeAppURL = {
  ios: '<id of an app store app>',
  android: 'market://details?id=<package_name>',
  windows: 'ms-windows-store://pdp/?ProductId=<the apps Store ID>',
  blackberry: 'appworld://content/[App Id]/',
  windows8: 'ms-windows-store:Review?name=<the Package Family Name of the application>'
};

AppRate.preferences.customLocale = {
  title: 'Leave a Review',
  message: 'If you like the game, consider giving it 5 stars!',
  cancelButtonLabel: 'Pass',
  rateButtonLabel: 'Rate it!',
  laterButtonLabel: 'Later'
};

AppRate.promptForRating();
```

Popup appeared, clicking "Rate it!" led to the App Store.

**Comment by Panajev** [comment] 2017-02-15 10:59
Are you using a custom popup UI?

**Comment by PetruMagdeleine** [comment] 2017-02-22 16:57
Hi Panajev,

Same problem with ios 10.2+ (using ionic app / no custom popup UI).
I used your snippet and the Popup appeared. Clicking "Rate it" only close it. No error message.

**Comment by harshabonthu** [comment] 2017-02-23 23:32
I see the same issue, i.e Clicking on Rate it popup closes but doesn't redirect to Appstore. Not sure if this is the cause (https://github.com/pushandplay/cordova-plugin-apprate/pull/127) but adding back inappBrowser plugin worked i.e now it redirects to appstore.

**Comment by westonganger** [comment] 2017-05-09 15:48
v1.3.0 release which fixes this.

**Closed by westonganger** 2017-05-09 15:48 UTC
