### ISSUE TITLE
Andriod-PhoneGap : Issue Rate button text truncate

### ISSUE THREAD

**Issue by karamveer-cipl** [pushandplay/cordova-plugin-apprate#112] opened 2016-03-18 14:27 UTC
Hello Support Team,

I am working on Andriod-Phonegap application and facing some challenges over there,

Issue: Rate-It now button truncated on some Android versions, Button not working fine with all Android versions and also not working responsively.

Please let me know if anyone faced same challenges, looking forward for response/fixes asap.

Regards,
Karamveer Singh
##

**Comment by hlehmann** [comment] 2016-03-23 12:03
I have got the same, on android, buttons are placed in line instead of one per line.

**Comment by westonganger** [comment] 2017-05-09 15:56
Duplicate of #98 and #63

**Closed by westonganger** 2017-05-09 15:56 UTC
