### ISSUE TITLE
'Write A Review' button not working

### ISSUE THREAD

**Issue by ohh2ahh** [pushandplay/cordova-plugin-apprate#71] opened 2015-02-05 18:56 UTC
Today I noticed that the 'Write A Review' button in the opened in-app store is not working on iOS. The rest of plugin works like a charm. Does anyone other have this issue?
- Tested on a real devices with iOS 8.1.2 and 8.1.3
- Cordova 4.2.0
- Cordova iOS 3.7.0
- `StoreKit.framework` is linked in Xcode
##

**Comment by pushandplay** [comment] 2015-02-05 19:14
@ohh2ahh Hi, can you show me code of initialisation and invocation of plugin?

**Comment by ohh2ahh** [comment] 2015-02-05 19:21
Thank you @pushandplay for your ultra fast response.

Here's my code (running in `app.receivedEvent('deviceready');`):

```js
if(typeof AppRate !== 'undefined') {
    var onRateDialogShow = function(callback) {
        console.log('AppRate Dialog shown');
    };

    AppRate.preferences.useLanguage = en;
    AppRate.preferences.openStoreInApp = true;
    AppRate.preferences.storeAppURL.ios = '##########';
    AppRate.preferences.storeAppURL.android = 'market://details?id=com.domain.app';
    AppRate.preferences.usesUntilPrompt = 5;
    AppRate.preferences.promptAgainForEachNewVersion = true;
    AppRate.preferences.callbacks.onRateDialogShow = onRateDialogShow;
    AppRate.promptForRating(true);
}
else {
    console.log('AppRate plugin could not be loaded.');
}
```

**Comment by pushandplay** [comment] 2015-02-05 20:24
@ohh2ahh 
1.<code>AppRate.preferences.useLanguage</code> - require string type
2. Check if installed org.apache.cordova.inappbrowser
3. Fill <code>AppRate.preferences.storeAppURL.ios</code> field with correct URL if you want testing on iOS
4.<code>if(typeof AppRate !== 'undefined')...</code> wtf? read about events - http://cordova.apache.org/docs/en/4.0.0/cordova_events_events.md.html#deviceready

**Comment by ohh2ahh** [comment] 2015-02-05 20:46
1. Sorry, I made that mistake while pasting the code here.
2. Already installed and working.
3. I anonymized the identities before posting my code.

It's weird that everything else is working. For now, I'm using `AppRate.preferences.openStoreInApp = false;` as a workaround.

**Comment by pushandplay** [comment] 2015-02-05 20:59
@ohh2ahh <code>AppRate.preferences.openStoreInApp</code> with true value available only on iOS and require valid app url

**Comment by ohh2ahh** [comment] 2015-02-05 21:21
@pushandplay That was clear for me. With `AppRate.preferences.openStoreInApp = true;` the **in-app store** shows correctly and displays my app on the description / screenshot page - so that works perfectly. But when I tap on 'Reviews' and then on 'Write a Review' the review modal never shows. Maybe it's a bug in the iOS SDK or StoreKit.framework.

![issue-71](https://cloud.githubusercontent.com/assets/2352329/6069402/44702a0e-ad84-11e4-9be1-d115591167ef.png)

**Comment by pushandplay** [comment] 2015-02-07 11:48
@ohh2ahh I think this is bug of StoreKit.framework

**Comment by novakben** [comment] 2015-03-14 20:04
Same issue here. Anyone resolved this?

**Comment by pushandplay** [comment] 2015-04-03 06:28
This is iOS issue and this is a bug of StoreKit.framework. It is not have a solution now

**Comment by cavalleydude** [comment] 2016-03-31 17:08
I'm having the same issue, thanks @ohh2ahh for logging this. Everything else in the plugin appears to be working well except this issue on iOS. I'm using Cordova 3.8.0, iOS 9.3, on iPhone 6 Plus. I'm hoping there is a fix for this soon. In the meantime, I'm also using the workaround suggested above.

**Comment by ivanov84** [comment] 2016-04-06 21:59
+1

**Comment by akofman** [comment] 2016-06-20 22:42
It looks like you won't have any fix and should keep the workaround http://stackoverflow.com/questions/36544926/does-skstoreproductviewcontroller-allow-to-rate-an-app-write-a-review

**Closed** 2017-05-09 15:30 UTC
Labels: question
